<a href="https://colab.research.google.com/github/DISHANTJOSHI1/dishant_data690/blob/main/assignment_05/part_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 05: Part 4- Intro to NumPy
- Name: Dishant  Fapot
- Date: 03/05/2022

1. What is NumPy?
- One of the core packages for numerical computing in Python
- Performs efficient numeric computation with C primitives, efficient collections with vectorized operations, an integrated and natural linear algebra API, and a C API for connecting NumPy with libraries written in other languages
- Uses primitive numeric types (floats and ints) which allows for easy storage and computation

2.Where is NumPy involved?

- Normal Python wastes data with simple numeric operations due to object orientations
- NumPy creates numbers with controlled sizes in terms of bits, which helps with high level processing
- NumPy mainly processes arrays, which are optimized for high level computing, as opposed to Python lists, which wrap numbers in objects and make low level instructions difficult to efficiently process

In [1]:
import sys
import numpy as np

Numpy Arrays

In [2]:
a= np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

array types

In [9]:
a.dtype

dtype('int64')

In [10]:
b.dtype

dtype('float64')

In [12]:
np.array([1, 2, 3, 4], dtype=np.float) # convert to float

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [13]:
np.array([1, 2, 3, 4], dtype=np.int8) # Convert to int

array([1, 2, 3, 4], dtype=int8)

In [14]:
d = np.array([{'a':1}, sys])

In [15]:
d.dtype

dtype('O')

Dimension and shape

In [17]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [18]:
A.shape

(2, 3)

In [20]:
A.ndim # number of dimensions (axes) of the ndarray

2

In [21]:
A.size

6

In [22]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [23]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [24]:
B.shape

(2, 2, 3)

In [25]:
B.size

12

In [26]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [27]:
C.dtype

dtype('O')

In [28]:
C.shape

(2,)

In [29]:
C.size

2

In [30]:
C.ndim

1

In [31]:
type(C[0])

list

Indexing and Slicing of Matrices

In [32]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [33]:
A[1]

array([4, 5, 6])

In [34]:
A[1][0]

4

In [35]:
A[1] = np.array([10, 10, 10])

In [36]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [43]:
A[1]

array([4, 5, 6])

In [44]:
A[1][0]

4

In [45]:
A[1, 0]

4

In [46]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [48]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [50]:
A[:2, 2:]

array([[3],
       [6]])

In [51]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
A[2] = 99

In [53]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

Summary statistics


In [54]:
a = np.array([1, 2, 3, 4])

In [55]:
a.sum()

10

In [56]:
a.min()

1

In [57]:
a.max()

4

In [58]:
a.std()

1.118033988749895

In [59]:
a.var()

1.25

In [60]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [63]:
A.sum()

45

In [64]:
A.mean()

5.0

In [65]:
A.std()

2.581988897471611

In [66]:
A.sum(axis=0)

array([12, 15, 18])

In [67]:
A.sum(axis=1)

array([ 6, 15, 24])

In [68]:
A.mean(axis=0)

array([4., 5., 6.])

In [69]:
A.mean(axis=1)

array([2., 5., 8.])

In [70]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [71]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

Broadcasting and Vectorized operations

In [72]:
a = np.arange(4)

In [73]:
a

array([0, 1, 2, 3])

In [74]:
a+2

array([2, 3, 4, 5])

In [75]:
a*2

array([0, 2, 4, 6])

In [76]:
a

array([0, 1, 2, 3])

In [77]:
a+=100

In [78]:
a

array([100, 101, 102, 103])

In [79]:
l = [0, 1, 2, 3]

In [80]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [81]:
a = np.arange(4)

In [82]:
a

array([0, 1, 2, 3])

In [83]:
b = np.array([10, 10, 10, 10])

In [85]:
b

array([10, 10, 10, 10])

In [84]:
a+b

array([10, 11, 12, 13])

Boolean arrays

In [86]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [87]:
a[0], a[-1]

(0, 3)

In [88]:
a[[0, -1]]

array([0, 3])

In [89]:
a[[True, False, False, True]]

array([0, 3])

In [90]:
a

array([0, 1, 2, 3])

In [91]:
a >= 2

array([False, False,  True,  True])

In [92]:
a[a >= 2]

array([2, 3])

In [93]:
a[a > a.mean()]

array([2, 3])

In [94]:
a[~(a > a.mean())]

array([0, 1])

In [97]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [98]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [100]:
A = np.random.randint(100, size=(3, 3))
A

array([[91, 79, 42],
       [84, 24, 62],
       [84, 88, 70]])

In [101]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([91, 42, 24, 84, 70])

In [102]:
A > 30

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [103]:
A[A > 30]

array([91, 79, 42, 84, 62, 84, 88, 70])

Linear Algebra

In [104]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [106]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [107]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [108]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [109]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [110]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Size of objects in Memory

In [112]:
sys.getsizeof(1)

28

In [114]:
sys.getsizeof(10**100)

72

In [115]:
np.dtype(int).itemsize

8

In [116]:
np.dtype(np.int8).itemsize

1

In [117]:
np.dtype(float).itemsize


8

For larger lists

In [118]:
sys.getsizeof([1])

80

In [119]:
np.array([1]).nbytes

8

In [120]:
l = list(range(100000))

In [121]:
a = np.arange(100000)

In [122]:
%time np.sum(a ** 2)

CPU times: user 599 µs, sys: 2 ms, total: 2.6 ms
Wall time: 2.13 ms


333328333350000

In [123]:
%time sum([x ** 2 for x in l])

CPU times: user 36.4 ms, sys: 2.48 ms, total: 38.9 ms
Wall time: 39.5 ms


333328333350000

Usefull Numpy Functions

1. random

In [124]:
np.random.random(size=2)

array([0.50719298, 0.4838511 ])

In [125]:
np.random.normal(size=2)

array([-0.04101489,  0.33118378])

In [126]:
np.random.rand(2, 4)

array([[0.80317252, 0.65801735, 0.20807627, 0.55901604],
       [0.15805277, 0.94043742, 0.01636199, 0.32143738]])

2. arange

In [127]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [129]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

3. reshape

In [130]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [131]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

4. linspace

In [134]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [135]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [136]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

5. zeros, ones, empty

In [137]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [138]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [139]:
np.zeros((3, 3), dtype=np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [140]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [141]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [142]:
  np.empty(5)

array([1., 1., 1., 1., 1.])

In [143]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

identity and eye

In [144]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [145]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [146]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [147]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [148]:
"Hello World"[6]

'W'